Copy and remove kubeconfig when cluster created.

diff --git a/scripts/deploy_k3s b/scripts/deploy_k3s
--- a/scripts/deploy_k3s
+++ b/scripts/deploy_k3s
@@ -3,6 +3,7 @@
 TOPLEVEL=$(git rev-parse --show-toplevel)
 DEFAULT_REPROVISION=false
 DEFAULT_VAGRANT_CWD="$TOPLEVEL/infra/k3s"
+PATH_TO_TEMP_KUBECONFIG="/tmp/k3s-kubeconfig"
 export VAGRANT_CWD="${VAGRANT_CWD:-$DEFAULT_VAGRANT_CWD}"
 export REPROVISION="${REPROVISION:-$DEFAULT_REPROVISION}"
 
@@ -61,6 +62,21 @@ configure_nodes() {
       "/work/site.yml"
 }
 
+fetch_kubeconfig_for_master() {
+  command="vagrant ssh k3s-node-0 -c 'sudo cat /etc/rancher/k3s/k3s.yaml > $PATH_TO_TEMP_KUBECONFIG'"
+  if ! eval "$command"
+  then
+    >&2 echo "ERROR: Failed to write kubeconfig locally. Try running it manually: \
+$command"
+    exit 1
+  fi
+}
+
+provide_kubectl_instructions() {
+  echo "INFO: Use 'kubectl --kubeconfig=$PATH_TO_TEMP_KUBECONFIG' to access your \
+new k3s cluster."
+}
+
 if [ "$1" == '--help' ] || [ "$1" == '-h' ]
 then
   usage
@@ -73,4 +89,6 @@ then
   exit 1
 fi
 
-generate_ssh_keypair && provision_nodes && configure_nodes
+generate_ssh_keypair && provision_nodes && configure_nodes &&
+  fetch_kubeconfig_for_master &&
+  provide_kubectl_instructions
