Warn when kubectl and helm not installed.

diff --git a/scripts/deploy_k3s b/scripts/deploy_k3s
--- a/scripts/deploy_k3s
+++ b/scripts/deploy_k3s
@@ -72,6 +72,13 @@ $command"
   fi
 }
 
+check_for_kubectl_and_helm() {
+  if ! &>/dev/null which kubectl || ! &>/dev/null which helm
+  then
+    >&2 echo "WARN: kubectl and/or helm not found"'!'
+  fi
+}
+
 provide_kubectl_instructions() {
   echo "INFO: Use 'kubectl --kubeconfig=$PATH_TO_TEMP_KUBECONFIG' to access your \
 new k3s cluster."
@@ -90,5 +97,5 @@ then
 fi
 
 generate_ssh_keypair && provision_nodes && configure_nodes &&
-  fetch_kubeconfig_for_master &&
+  fetch_kubeconfig_for_master && check_for_kubectl_and_helm &&
   provide_kubectl_instructions
